name: OpenWrt Second Compilation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: owrt
          fetch-depth: 0

      - name: Update Source
        run: git pull --ff-only origin owrt || true

      - name: Quick Feeds Update
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load Config & Fix tcping
        run: |
          cp s20m.config .config
          echo "# CONFIG_PACKAGE_tcping is not set" >> .config
          make defconfig

      - name: Compile Firmware
        run: |
          make -j$(($(nproc) + 1)) V=s || make -j2 V=s

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt-S20M-Second-Build
          path: bin/targets/*
          retention-days: 30
