name: OpenWrt Second Compilation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: owrt
          fetch-depth: 0

      - name: Update Source
        run: git pull --ff-only origin owrt || true

      - name: Quick Feeds Update
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Compile Firmware
        run: |
          # 绕过 tcping 的 strip 错误
          export STRIP="true"
          echo "已临时禁用 STRIP 工具以绕过 tcping 错误"
          
          make -j$(($(nproc) + 1)) V=s || make -j2 V=s

      - name: Compile Firmware
        run: |
          make -j$(($(nproc) + 1)) V=s || make -j2 V=s

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt-S20M-Second-Build
          path: bin/targets/*
          retention-days: 30
